[package]
name = "zkauth-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
num-bigint = { version = "0.4.4", features = ["rand"] }
num-traits = "0.2.18"
rand = "0.8.5"
sha2 = "0.10.8"
tonic = "0.11.0"
zkauth-pb = { path = "../zkauth-pb", features = ["full"] }
